# НАСТРОЙКИ API Битопа
[BITOP]
SiteAdress = "api.bistg.bmstu.ru"
Protocol = "https"
PathPath = "/schedule/"
PathSearch = "/search/unit"

# НАСТРОЙКИ РЕДИСКИ
[Redis]
# Таймауты в миллисекундах
DialTimeout = 100
ReadTimeout = 100
Host="0.0.0.0"
Port=6379